{
 "title": "Subsquid monitoring dashboard",
 "tags": [ "Subsquid" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Node status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "worker_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node info",
   "type": "table",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "worker_info_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_successful_queries_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_successful_queries_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_server_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stored data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "stored_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Downloaded data",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "downloaded_bytes_sum", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Downloaded files",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_successful_downloads_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Virtual memory size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{group=\"subsquid\"} / (1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident memory size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{group=\"subsquid\"} / (1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resident memory size",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{group=\"subsquid\"} / (1024*1024*1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total user and system CPU time spent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{group=\"subsquid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of open file descriptors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_open_fds{group=\"subsquid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maximum number of open file descriptors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_max_fds{group=\"subsquid\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Python data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Python version",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "python_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of times this generation was collected (GC)",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 11 },
   "targets": [
    { "expr": "python_gc_collections_total", "legendFormat": "Generation {{generation}}" }
   ]
  },
  {
   "title": "Total objects collected during gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "python_gc_objects_collected_total",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  {
   "title": "Total uncollectable objects found during GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "python_gc_objects_uncollectable_total",
     "legendFormat": "Generation {{generation}}"
    }
   ]
  },
  { "title": "Downloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Number of download errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_download_errors_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Number of successfull downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_successful_downloads_total", "legendFormat": "__auto" }
   ]
  }
 ]
}